language: node_js
node_js:
- '7'
before_script:
  - npm install -g bower
script:
- bower install
- npm install
- ember build --environment=production
cache:
  directories:
    - node_modules
deploy:
  local_dir: dist/
  provider: pages
  skip_cleanup: true
  repo: feuerwehr-molsdorf/feuerwehr-molsdorf.github.io
  target_branch: master
  github_token: "$GITHUB_TOKEN"
  on:
    branch: master
env:
  global:
  - secure: KsxelvTpYtZb6jUKxip9IzlEFiNi8B2hvgid5KlWvBsLYsGGgLq9k4qEj/4a+LUVn+5tnaNRVNXhSQWuH0Wkchyg77jU50UT8adwo2r5AS4LO1Hct0AANVJlT0336Mh55vBqllwcPujOVPGnZrZzksQzTnCWAgyWdW5b7Ojf3Gi2Rd8ZjqQ4STZYVKh+lb8efFbjWboguwz7QUsBDqe/33bNRmVoNv4Q6f5D8jNMoBYNdXaBff2syJo4EaQFXH82oFcJ61Tmb048w4ZDICne0gulQw1fESp963ikQUmR8MRZyNmeqhdjwvFlEctkEJ9AkK/M56bu2ipluVZjBSEW+Kd5R5zOIdZcA0PVJuTxbacMz6fxOii0kbpDy1X38LnVqxhpIVHpemw3QBAaE5NezT6R5VNwiiDhAghRm6MmhEAsKOyZVIIbQK2ZR8oARx6QU4j7TZzjZGgrLPYBRHZ8WsQJpPKuw6QFdUTPx/OhQ0Ct3LYITc21Fish1wn3Md7ez4JnwMzKd93qKXiT+j1L7r3yqqDY+hh98t5TpqWzBe+gBwV205ZW3bpcU4w5gQKmNjOlSci3oFUbNMUYVF8Fotd0icsoGAbegvFFW/8GHmS7j+Y4+i3RJ3yVz+WcxLoNTycsqbCm7dM0Fj1j2uARNzx4LCmILVMYdlfqEqo7fys=
  - secure: qj0fgqcAf/aypLqlX5Mqelb1TUc0BYqMEwMIfukydzH+3zxjTIKs/FJbtahCv6g8K/ZxTGlJt52hw0H020LbCG19Zb9vSwov3z9pNhsRmlHb5cHq4XdhkDUuu7FrVDStBvnEsRTWihbMKhjr5ILK9sMbLdBgXebWah3d8tYutjfWbj7s5Feq1gYT8Lomh8OAxk+zKa5GGrlg00+j8n6STFZgqEgXmua75yB0waGnQNaLw03dVlIHPujGCQyk2XapbQfpUSxz50oPfy71Xz/QW7b1l2MKuBr+SIBfQ4yG3++e6xTm5T5BI5ip1O8OrHh3BXSIF8JZlSh/U4GtswaM6dlK/Cx7K4ExE9RYNn4G1btMpuVVWjMqbixknKbxK2wOLbyiNKYmn8kpFkr4V9hqJ9Xwfb1d2b6/Yivl/8jSiEJa/SLZ7Cu9jDjsiQhmXs6OxwsU6Cwzz9Ep9KyD6TVgyhk6CIFzkzRwTBrCGGdosd/xDaWLhfGM72dYjqIQuWi3o2+JEe17kKolSKdHf+BUpq7JiJjX2WqNR18nFn1OXmiUy3Qdq1Oi6G+v3vn1jPMcZwwskISd0NaS+Ob3eL4poQtePm57+68azTNFDKbTjDATjonKtgmcjOOoJJTPYC/5liHs+bi5tJPYELCMIiyx5CC3mYP25xNnf88or0iSPCE=
