---
language: node_js
node_js:
  - "10"

addons:
  chrome: stable

cache:
  directories:
    - $HOME/.npm
    - node_modules

before_install:
  - npm config set spin false

before_script:
  - npm install -g bower
  - bower install

script:
  - npm run lint:hbs
  - npm run lint:js
  - npm test
  - ember build --environment=production

deploy:
  local_dir: dist/
  provider: pages
  skip_cleanup: true
  repo: feuerwehr-molsdorf/feuerwehr-molsdorf.github.io
  target_branch: master
  github_token: "$GITHUB_TOKEN"
  on:
    branch: master