language: node_js
node_js:
- '7'
before_script:
  - npm install -g bower
script:
- bower install
- npm install
- ember build
deploy:
  local_dir: dist/
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
env:
  global:
    secure: KsxelvTpYtZb6jUKxip9IzlEFiNi8B2hvgid5KlWvBsLYsGGgLq9k4qEj/4a+LUVn+5tnaNRVNXhSQWuH0Wkchyg77jU50UT8adwo2r5AS4LO1Hct0AANVJlT0336Mh55vBqllwcPujOVPGnZrZzksQzTnCWAgyWdW5b7Ojf3Gi2Rd8ZjqQ4STZYVKh+lb8efFbjWboguwz7QUsBDqe/33bNRmVoNv4Q6f5D8jNMoBYNdXaBff2syJo4EaQFXH82oFcJ61Tmb048w4ZDICne0gulQw1fESp963ikQUmR8MRZyNmeqhdjwvFlEctkEJ9AkK/M56bu2ipluVZjBSEW+Kd5R5zOIdZcA0PVJuTxbacMz6fxOii0kbpDy1X38LnVqxhpIVHpemw3QBAaE5NezT6R5VNwiiDhAghRm6MmhEAsKOyZVIIbQK2ZR8oARx6QU4j7TZzjZGgrLPYBRHZ8WsQJpPKuw6QFdUTPx/OhQ0Ct3LYITc21Fish1wn3Md7ez4JnwMzKd93qKXiT+j1L7r3yqqDY+hh98t5TpqWzBe+gBwV205ZW3bpcU4w5gQKmNjOlSci3oFUbNMUYVF8Fotd0icsoGAbegvFFW/8GHmS7j+Y4+i3RJ3yVz+WcxLoNTycsqbCm7dM0Fj1j2uARNzx4LCmILVMYdlfqEqo7fys=
